apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ingress-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
